version: '3'
services:
  mobispaces-pa-visualization:
    build: .
    container_name: pa-visualization
    ports:
      - 80:80
    volumes:
      - ".:/usr/src/app/app"
    restart: unless-stopped
#   database:
#     image: postgres:latest
#     volumes: 
#       - db-data:/var/lib/postgresql/data
#     container_name: postgres_db
#     environment:
#       - POSTGRES_DB=pa-visualization
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - 5432:5432
#     restart: unless-stopped
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - 8888:8080
volumes:
  db-data: {}
