# ship_types.py

ship_types = {
    10: "Reserved",
    11: "Reserved",
    12: "Reserved",
    13: "Reserved",
    14: "Reserved",
    15: "Reserved",
    16: "Reserved",
    17: "Reserved",
    18: "Reserved",
    19: "Reserved",
    20: "Wing In Grnd",
    21: "Wing In Grnd",
    22: "Wing In Grnd",
    23: "Wing In Grnd",
    24: "Wing In Grnd",
    25: "Wing In Grnd",
    26: "Wing In Grnd",
    27: "Wing In Grnd",
    28: "Wing In Grnd",
    29: "SAR Aircraft",
    30: "Fishing",
    31: "Tug",
    32: "Tug",
    33: "Dredger",
    34: "Dive Vessel",
    35: "Military Ops",
    36: "Sailing Vessel",
    37: "Pleasure Craft",
    38: "Reserved",
    39: "Reserved",
    40: "High-Speed Craft",
    41: "High-Speed Craft",
    42: "High-Speed Craft",
    43: "High-Speed Craft",
    44: "High-Speed Craft",
    45: "High-Speed Craft",
    46: "High-Speed Craft",
    47: "High-Speed Craft",
    48: "High-Speed Craft",
    49: "High-Speed Craft",
    50: "Pilot Vessel",
    51: "SAR",
    52: "Tug",
    53: "Port Tender",
    54: "Anti-Pollution",
    55: "Law Enforce",
    56: "Local Vessel",
    57: "Local Vessel",
    58: "Medical Trans",
    59: "Special Craft",
    60: "Passenger",
    61: "Passenger",
    62: "Passenger",
    63: "Passenger",
    64: "Passenger",
    65: "Passenger",
    66: "Passenger",
    67: "Passenger",
    68: "Passenger",
    69: "Passenger",
    70: "Cargo",
    71: "Cargo - Hazard A (Major)",
    72: "Cargo - Hazard B",
    73: "Cargo - Hazard C (Minor)",
    74: "Cargo - Hazard D (Recognizable)",
    75: "Cargo",
    76: "Cargo",
    77: "Cargo",
    78: "Cargo",
    79: "Cargo",
    80: "Tanker",
    81: "Tanker - Hazard A (Major)",
    82: "Tanker - Hazard B",
    83: "Tanker - Hazard C (Minor)",
    84: "Tanker - Hazard D (Recognizable)",
    85: "Tanker",
    86: "Tanker",
    87: "Tanker",
    88: "Tanker",
    89: "Tanker",
    90: "Other",
    91: "Other",
    92: "Other",
    93: "Other",
    94: "Other",
    95: "Other",
    96: "Other",
    97: "Other",
    98: "Other",
    99: "Other",
}
